Rasa process starting
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again Sharan
Sending message: Goodbye
Sending message: Hey, nice to meet you again Hi
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again None
Sending message: Hey, nice to meet you again None
Sending message: Hey, nice to meet you again None
Sending message: Goodbye
Sending message: Hey, nice to meet you again None
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again Sharan
Sending message: Goodbye
Sending message: Hey, nice to meet you again Hi
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:80
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again None
Sending message: Hey, nice to meet you again None
Sending message: Hey, nice to meet you again None
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Sending message: Hey, nice to meet you again None
Sending message: Goodbye
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again Sharan
Sending message: Goodbye
Sending message: Hey, nice to meet you again Hi
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Rasa process starting
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002
Sending message: Hey, nice to meet you. What's your name?
Sending message: Hey, nice to meet you again sharan
Sending message: Hey, nice to meet you again sharan
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 279, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/freeradical/anaconda3/envs/pyfor36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 254, in handle
    for message in entry['messaging']:
KeyError: 'messaging'
